# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lraggio <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/12 15:58:04 by lraggio           #+#    #+#              #
#    Updated: 2023/08/13 20:37:46 by lraggio          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Wextra -Werror
SOURCES = functions.c rush-02.c arquive.c
EXECUTABLES = a.out

all: # o alvo que a gente quer mexer (normalmente é o programa em si), essa parte vai direcionar os comandos p/ mexer com essa parte específica

clean: # inserir o nome dos arquivos que a gente gera ao mexer no editor, mas que não queremos entregar à Moulinette

fclean: clean
# Adicionar comandos p/ remover arquivos de forma automatizada
# ex: rm -f test.txt
